### ISSUE TITLE
Division by Zero

### ISSUE THREAD

**Issue by dambridge** [jenssegers/codeigniter-advanced-images#1]
I am getting the following error:

> Severity: Warning
> 
> Message: Division by zero
> 
> Filename: libraries/MY_Image_lib.php
> 
> Line Number: 99

If I turn off error_reporting in the Media controller, I will see the image; however, it will not be resized.

**Comment by jenssegers** [comment]
It seems that the original Image library was unable to get the original dimensions.

**Comment by jenssegers** [comment]
This can be fixed like this:
https://github.com/segersjens/CodeIgniter-Advanced-Images/commit/6f0ab732aaf9a815001779e477167f78d7258b09
